[package]
name = "rust_data_inspector_signals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.11.1"
serde = {version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
